# Generated by Django 5.2 on 2025-04-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('is_associate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evaluated',
                'verbose_name_plural': 'Evaluated',
            },
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evaluator',
                'verbose_name_plural': 'Evaluators',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('estagio_mudanca', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')])),
                ('estrutura', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')])),
                ('encerramento', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')])),
                ('acolhimento', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')])),
                ('seguranca_terapeuta', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')])),
                ('seguranca_metodo', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')])),
                ('aprofundar', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')])),
                ('hipoteses', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')])),
                ('interpretativa', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')])),
                ('frase_timing', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')])),
                ('corpo_setting', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')])),
                ('insight_potencia', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')])),
                ('evaluated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='avaliacao.evaluated')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='avaliacao.evaluator')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'ordering': ['-evaluation_date'],
            },
        ),
    ]
